import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Link from "next/link";
import { Archive, Heart, PaintBucket } from "lucide-react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const sidebarData = [
  {
    title: "Generator",
    path: "/",
    icon: <PaintBucket className="h-4 w-4" />,
  },
  {
    title: "Palletes",
    path: "/palletes",
    icon: <Archive className="h-4 w-4" />,
  },
  {
    title: "Favourites",
    path: "/favourites",
    icon: <Heart className="h-4 w-4" />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="bg-primary text-neutral-950">
            {/* Fixed Navbar */}
            <nav className="border-line bg-primary fixed top-0 right-0 left-0 z-50 flex h-14 items-center justify-between gap-20 border-b px-8">
              <h3 className="flex-none text-xl font-semibold">Colorfuse</h3>
              <input
                placeholder="Search palettes"
                className="border-line-dark/50 h-[65%] w-1/2 flex-1 rounded-full border ps-8 text-sm outline-none"
                type="text"
              />
            </nav>

            {/* Sidebar + main */}
            <div className="flex pt-14">
              {/* Fixed Left Sidebar */}
              <aside className="fixed top-14 left-0 h-[calc(100vh-3.5rem)] w-56 p-3">
                <div className="grid gap-3">
                  {sidebarData.map((page) => {
                    return (
                      <Link key={page.title} href={page.path}>
                        <div className="flex items-center gap-3 rounded-xl bg-amber-200/30 p-3 hover:text-neutral-700">
                          {page.icon}
                          {page.title}
                        </div>
                      </Link>
                    );
                  })}
                </div>
              </aside>

              {/* Fixed Right Sidebar */}
              <aside className="border-line-dark/50 fixed top-14 right-0 h-[calc(100vh-3.5rem)] w-64 border-l p-3">
                <h4 className="text-lg font-medium">
                  Smart Color Generator for Designers
                </h4>
                <h6 className="text-sm tracking-tight">
                  Pick colors, blend gradients, and find the perfect palette for
                  any project in seconds.
                </h6>
              </aside>

              {/* Main Content */}
              <main className="mx-[284px] w-full bg-red-200">
                {/* 56px (left) + 56px (right) */}
                <div className="min-h-[200vh] rounded-xl p-6">{children}</div>
              </main>
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
